// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eprvbtrqsxecugufmjri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwcnZidHJxc3hlY3VndWZtanJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MjEyMDMsImV4cCI6MjA2MzE5NzIwM30.MW74Ri6p68EouX1dKqdMKpgK0ukCnmx-KjoE4HhVY-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);